export const enum ErrorCodes {
  ERROR_INVALID_RESIZE_WIDTH = 'ERROR_INVALID_RESIZE_WIDTH',
  ERROR_INVALID_RESIZE_HEIGHT = 'ERROR_INVALID_RESIZE_HEIGHT',
  ERROR_INVALID_URL = 'ERROR_INVALID_URL',
  ERROR_MISSING_RESIZE_WIDTH_OR_HEIGHT = 'ERROR_MISSING_RESIZE_WIDTH_OR_HEIGHT',
}
